# fly.toml app configuration file generated for traffic-generator on 2025-01-27T17:07:35+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'traffic-generator'
primary_region = 'ams'

[metrics]
  port = 9090
  path = "/metrics"

[processes]
  worker = 'npm run start'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1024mb'
  cpu_kind = 'dedicated'
  cpus = 2
